site_name: Library of Aleksander
site_description: 'The Library of Aleksander'
site_author: 'Christian Albert'
docs_dir: docs/
repo_name: 'calbert1209/library_of_aleksander'
repo_url: 'https://github.com/calbert1209/library_of_aleksander'
nav:
    - Home: index.md
    - 'The End of Evil': './The_End_of_Evil/index.md'
    - 'Tools for Conviviality': './Tools_for_Conviviality/index.md'
theme:
  name: 'material'
  palette:
    primary: blue grey
  icon:
    logo: fontawesome/solid/building-columns
  favicon: assets/building-columns-solid.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
